# -*- coding: utf-8 -*-
"""
Created on Thu Jul 27 07:47:30 2017

@author: casari
"""
from pyqtgraph.Qt import QtCore, QtGui,QtWidgets
from pyqtgraph import GraphicsLayoutWidget
#from PyQt5.Qt import QWidgets

class Ui_QIcmGuiMainWindow(object):
    def setupUi(self, QIcmGuiMainWindow):
        QIcmGuiMainWindow.setObjectName("QIcmGuiMainWindow")
        QIcmGuiMainWindow.resize(1200,892)
        self.centralwidget = QtWidgets.QWidget(QIcmGuiMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.plotSplitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotSplitter.sizePolicy().hasHeightForWidth())
        self.plotSplitter.setSizePolicy(sizePolicy)
        self.plotSplitter.setOrientation(QtCore.Qt.Vertical)
        self.plotSplitter.setObjectName("plotSplitter")
        
        self.mainPlotLayout = GraphicsLayoutWidget(self.plotSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainPlotLayout.sizePolicy().hasHeightForWidth())
        self.mainPlotLayout.setSizePolicy(sizePolicy)
        self.mainPlotLayout.setObjectName("mainPlotLayout")
        
        self.waterfallPlotLayout = GraphicsLayoutWidget(self.plotSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waterfallPlotLayout.sizePolicy().hasHeightForWidth())
        self.waterfallPlotLayout.setSizePolicy(sizePolicy)
        self.waterfallPlotLayout.setObjectName("waterfallPlotLayout")
        self.horizontalLayout.addWidget(self.plotSplitter)
        
        QIcmGuiMainWindow.setCentralWidget(self.centralwidget)
        
        
        self.menubar = QtWidgets.QMenuBar(QIcmGuiMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 32))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        QIcmGuiMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(QIcmGuiMainWindow)
        self.statusbar.setObjectName("statusbar")
        QIcmGuiMainWindow.setStatusBar(self.statusbar)
        
        
        self.controlsDockWidget = QtWidgets.QDockWidget(QIcmGuiMainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlsDockWidget.sizePolicy().hasHeightForWidth())
        self.controlsDockWidget.setSizePolicy(sizePolicy)
        self.controlsDockWidget.setMinimumSize(QtCore.QSize(190, 130))
        self.controlsDockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.controlsDockWidget.setObjectName("controlsDockWidget")
        self.controlsDockWidgetContents = QtWidgets.QWidget()
        self.controlsDockWidgetContents.setObjectName("controlsDockWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.controlsDockWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.startButton = QtWidgets.QPushButton(self.controlsDockWidgetContents)
        self.startButton.setObjectName("startButton")
        self.gridLayout_2.addWidget(self.startButton, 0, 0, 1, 1)
        self.stopButton = QtWidgets.QPushButton(self.controlsDockWidgetContents)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout_2.addWidget(self.stopButton, 0, 1, 1, 1)
        self.singleShotButton = QtWidgets.QPushButton(self.controlsDockWidgetContents)
        self.singleShotButton.setObjectName("singleShotButton")
        self.gridLayout_2.addWidget(self.singleShotButton, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 561, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.controlsDockWidget.setWidget(self.controlsDockWidgetContents)
        QIcmGuiMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.controlsDockWidget)

#        self.controlsDockWidget = QtWidgets.QDockWidget(QIcmGuiMainWindow)
#        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
#        sizePolicy.setHorizontalStretch(0)
#        sizePolicy.setVerticalStretch(0)
#        sizePolicy.setHeightForWidth(self.controlsDockWidget.sizePolicy().hasHeightForWidth())
#        self.controlsDockWidget.setSizePolicy(sizePolicy)
#        self.controlsDockWidget.setMinimumSize(QtCore.QSize(190, 130))
#        self.controlsDockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
#        self.controlsDockWidget.setObjectName("controlsDockWidget")
#        
#        #self.controlDockGridWidget = QGridLayout()
#        self.controlsDockWidgetContents = QtWidgets.QWidget()
#        self.controlsDockWidgetContents.setObjectName("controlsDockWidgetContents")
#        self.controlsDockWidget.setWidget(self.controlsDockWidgetContents)
#        QIcmGuiMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.controlsDockWidget)
        
#        QIcmGuiMainWindow.setCentralWidget(self.centralwidget)
        
#        self.gridLayout_2 = QtWidgets.QGridLayout(self.controlsDockWidgetContents)
#        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
#        self.gridLayout_2.setObjectName("gridLayout_2")
#        self.startButton = QtWidgets.QPushButton(self.controlsDockWidgetContents)
#        self.startButton.setObjectName("startButton")
#        self.gridLayout_2.addWidget(self.startButton, 0, 0, 1, 1)
#        self.stopButton = QtWidgets.QPushButton(self.controlsDockWidgetContents)
#        self.stopButton.setObjectName("stopButton")
#        self.gridLayout_2.addWidget(self.stopButton, 0, 1, 1, 1)
#        self.singleShotButton = QtWidgets.QPushButton(self.controlsDockWidgetContents)
#        self.singleShotButton.setObjectName("singleShotButton")
#        self.gridLayout_2.addWidget(self.singleShotButton, 1, 0, 1, 2)
#        spacerItem = QtWidgets.QSpacerItem(20, 561, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
#        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        


#        self.frequencyDockWidget = QtWidgets.QDockWidget(QIcmGuiMainWindow)
#        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
#        sizePolicy.setHorizontalStretch(0)
#        sizePolicy.setVerticalStretch(0)
#        sizePolicy.setHeightForWidth(self.frequencyDockWidget.sizePolicy().hasHeightForWidth())
#        self.frequencyDockWidget.setSizePolicy(sizePolicy)
#        self.frequencyDockWidget.setMinimumSize(QtCore.QSize(208, 166))
#        self.frequencyDockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
#        self.frequencyDockWidget.setObjectName("frequencyDockWidget")
#        self.frequencyDockWidgetContents = QtWidgets.QWidget()
#        self.frequencyDockWidgetContents.setObjectName("frequencyDockWidgetContents")
#        self.formLayout = QtWidgets.QFormLayout(self.frequencyDockWidgetContents)
#        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
#        self.formLayout.setContentsMargins(0, 0, 0, 0)
#        self.formLayout.setObjectName("formLayout")
#        self.label_2 = QtWidgets.QLabel(self.frequencyDockWidgetContents)
#        self.label_2.setObjectName("label_2")
#        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
#        self.startFreqSpinBox = QtWidgets.QDoubleSpinBox(self.frequencyDockWidgetContents)
#        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
#        sizePolicy.setHorizontalStretch(0)
#        sizePolicy.setVerticalStretch(0)
#        sizePolicy.setHeightForWidth(self.startFreqSpinBox.sizePolicy().hasHeightForWidth())
#        self.startFreqSpinBox.setSizePolicy(sizePolicy)
#        self.startFreqSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
#        self.startFreqSpinBox.setProperty("showGroupSeparator", True)
#        self.startFreqSpinBox.setDecimals(3)
#        self.startFreqSpinBox.setMinimum(0.0)
#        self.startFreqSpinBox.setMaximum(2200.0)
#        self.startFreqSpinBox.setProperty("value", 87.0)
#        self.startFreqSpinBox.setObjectName("startFreqSpinBox")
#        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.startFreqSpinBox)
#        self.label_3 = QtWidgets.QLabel(self.frequencyDockWidgetContents)
#        self.label_3.setObjectName("label_3")
#        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
#        self.stopFreqSpinBox = QtWidgets.QDoubleSpinBox(self.frequencyDockWidgetContents)
#        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
#        sizePolicy.setHorizontalStretch(0)
#        sizePolicy.setVerticalStretch(0)
#        sizePolicy.setHeightForWidth(self.stopFreqSpinBox.sizePolicy().hasHeightForWidth())
#        self.stopFreqSpinBox.setSizePolicy(sizePolicy)
#        self.stopFreqSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
#        self.stopFreqSpinBox.setProperty("showGroupSeparator", True)
#        self.stopFreqSpinBox.setDecimals(3)
#        self.stopFreqSpinBox.setMinimum(0.0)
#        self.stopFreqSpinBox.setMaximum(2200.0)
#        self.stopFreqSpinBox.setProperty("value", 108.0)
#        self.stopFreqSpinBox.setObjectName("stopFreqSpinBox")
#        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stopFreqSpinBox)
#        self.label = QtWidgets.QLabel(self.frequencyDockWidgetContents)
#        self.label.setObjectName("label")
#        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
#        self.binSizeSpinBox = QtWidgets.QDoubleSpinBox(self.frequencyDockWidgetContents)
#        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
#        sizePolicy.setHorizontalStretch(0)
#        sizePolicy.setVerticalStretch(0)
#        sizePolicy.setHeightForWidth(self.binSizeSpinBox.sizePolicy().hasHeightForWidth())
#        self.binSizeSpinBox.setSizePolicy(sizePolicy)
#        self.binSizeSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
#        self.binSizeSpinBox.setProperty("showGroupSeparator", True)
#        self.binSizeSpinBox.setDecimals(3)
#        self.binSizeSpinBox.setMinimum(0.0)
#        self.binSizeSpinBox.setMaximum(10000.0)
#        self.binSizeSpinBox.setProperty("value", 10.0)
#        self.binSizeSpinBox.setObjectName("binSizeSpinBox")
#        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.binSizeSpinBox)
#        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
#        self.formLayout.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
#        self.frequencyDockWidget.setWidget(self.frequencyDockWidgetContents)
#        QIcmGuiMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.frequencyDockWidget)
#        self.settingsDockWidget = QtWidgets.QDockWidget(QIcmGuiMainWindow)
#        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
#        sizePolicy.setHorizontalStretch(0)
#        sizePolicy.setVerticalStretch(0)
#        sizePolicy.setHeightForWidth(self.settingsDockWidget.sizePolicy().hasHeightForWidth())
#        self.settingsDockWidget.setSizePolicy(sizePolicy)
#        self.settingsDockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
#        self.settingsDockWidget.setObjectName("settingsDockWidget")
#        self.settingsDockWidgetContents = QtWidgets.QWidget()
#        self.settingsDockWidgetContents.setObjectName("settingsDockWidgetContents")
#        self.gridLayout = QtWidgets.QGridLayout(self.settingsDockWidgetContents)
#        self.gridLayout.setContentsMargins(0, 0, 0, 0)
#        self.gridLayout.setObjectName("gridLayout")
#        self.label_4 = QtWidgets.QLabel(self.settingsDockWidgetContents)
#        self.label_4.setObjectName("label_4")
#        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
#        self.label_6 = QtWidgets.QLabel(self.settingsDockWidgetContents)
#        self.label_6.setObjectName("label_6")
#        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)
#        self.intervalSpinBox = QtWidgets.QDoubleSpinBox(self.settingsDockWidgetContents)
#        self.intervalSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
#        self.intervalSpinBox.setMaximum(999.0)
#        self.intervalSpinBox.setProperty("value", 1.0)
#        self.intervalSpinBox.setObjectName("intervalSpinBox")
#        self.gridLayout.addWidget(self.intervalSpinBox, 1, 0, 1, 1)
#        self.label_5 = QtWidgets.QLabel(self.settingsDockWidgetContents)
#        self.label_5.setObjectName("label_5")
#        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
#        self.label_7 = QtWidgets.QLabel(self.settingsDockWidgetContents)
#        self.label_7.setObjectName("label_7")
#        self.gridLayout.addWidget(self.label_7, 2, 1, 1, 1)
#        self.ppmSpinBox = QtWidgets.QSpinBox(self.settingsDockWidgetContents)
#        self.ppmSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
#        self.ppmSpinBox.setMinimum(-999)
#        self.ppmSpinBox.setMaximum(999)
#        self.ppmSpinBox.setObjectName("ppmSpinBox")
#        self.gridLayout.addWidget(self.ppmSpinBox, 3, 0, 1, 1)
#        self.mainCurveCheckBox = QtWidgets.QCheckBox(self.settingsDockWidgetContents)
#        self.mainCurveCheckBox.setChecked(True)
#        self.mainCurveCheckBox.setObjectName("mainCurveCheckBox")
#        self.gridLayout.addWidget(self.mainCurveCheckBox, 4, 0, 1, 1)
#        self.colorsButton = QtWidgets.QPushButton(self.settingsDockWidgetContents)
#        self.colorsButton.setObjectName("colorsButton")
#        self.gridLayout.addWidget(self.colorsButton, 4, 1, 1, 2)
#        self.peakHoldMaxCheckBox = QtWidgets.QCheckBox(self.settingsDockWidgetContents)
#        self.peakHoldMaxCheckBox.setObjectName("peakHoldMaxCheckBox")
#        self.gridLayout.addWidget(self.peakHoldMaxCheckBox, 5, 0, 1, 1)
#        self.peakHoldMinCheckBox = QtWidgets.QCheckBox(self.settingsDockWidgetContents)
#        self.peakHoldMinCheckBox.setObjectName("peakHoldMinCheckBox")
#        self.gridLayout.addWidget(self.peakHoldMinCheckBox, 5, 1, 1, 2)
#        self.averageCheckBox = QtWidgets.QCheckBox(self.settingsDockWidgetContents)
#        self.averageCheckBox.setObjectName("averageCheckBox")
#        self.gridLayout.addWidget(self.averageCheckBox, 6, 0, 1, 1)
#        self.smoothCheckBox = QtWidgets.QCheckBox(self.settingsDockWidgetContents)
#        self.smoothCheckBox.setObjectName("smoothCheckBox")
#        self.gridLayout.addWidget(self.smoothCheckBox, 7, 0, 1, 1)
#        self.smoothButton = QtWidgets.QToolButton(self.settingsDockWidgetContents)
#        self.smoothButton.setAutoRaise(False)
#        self.smoothButton.setObjectName("smoothButton")
#        self.gridLayout.addWidget(self.smoothButton, 7, 2, 1, 1)
#        self.persistenceCheckBox = QtWidgets.QCheckBox(self.settingsDockWidgetContents)
#        self.persistenceCheckBox.setObjectName("persistenceCheckBox")
#        self.gridLayout.addWidget(self.persistenceCheckBox, 8, 0, 1, 1)
#        self.persistenceButton = QtWidgets.QToolButton(self.settingsDockWidgetContents)
#        self.persistenceButton.setAutoRaise(False)
#        self.persistenceButton.setObjectName("persistenceButton")
#        self.gridLayout.addWidget(self.persistenceButton, 8, 2, 1, 1)
#        spacerItem2 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
#        self.gridLayout.addItem(spacerItem2, 11, 0, 1, 1)
#        self.cropSpinBox = QtWidgets.QSpinBox(self.settingsDockWidgetContents)
#        self.cropSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
#        self.cropSpinBox.setObjectName("cropSpinBox")
#        self.gridLayout.addWidget(self.cropSpinBox, 3, 1, 1, 2)
#        self.gainSpinBox = QtWidgets.QDoubleSpinBox(self.settingsDockWidgetContents)
#        self.gainSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
#        self.gainSpinBox.setDecimals(1)
#        self.gainSpinBox.setMinimum(-1.0)
#        self.gainSpinBox.setMaximum(999.0)
#        self.gainSpinBox.setSingleStep(1.0)
#        self.gainSpinBox.setProperty("value", -1.0)
#        self.gainSpinBox.setObjectName("gainSpinBox")
#        self.gridLayout.addWidget(self.gainSpinBox, 1, 1, 1, 2)
#        self.baselineCheckBox = QtWidgets.QCheckBox(self.settingsDockWidgetContents)
#        self.baselineCheckBox.setObjectName("baselineCheckBox")
#        self.gridLayout.addWidget(self.baselineCheckBox, 9, 0, 1, 1)
#        self.baselineButton = QtWidgets.QToolButton(self.settingsDockWidgetContents)
#        self.baselineButton.setAutoRaise(False)
#        self.baselineButton.setObjectName("baselineButton")
#        self.gridLayout.addWidget(self.baselineButton, 9, 2, 1, 1)
#        self.subtractBaselineCheckBox = QtWidgets.QCheckBox(self.settingsDockWidgetContents)
#        self.subtractBaselineCheckBox.setObjectName("subtractBaselineCheckBox")
#        self.gridLayout.addWidget(self.subtractBaselineCheckBox, 10, 0, 1, 1)
#        self.settingsDockWidget.setWidget(self.settingsDockWidgetContents)
#        QIcmGuiMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.settingsDockWidget)
#        self.levelsDockWidget = QtWidgets.QDockWidget(QIcmGuiMainWindow)
#        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
#        sizePolicy.setHorizontalStretch(0)
#        sizePolicy.setVerticalStretch(0)
#        sizePolicy.setHeightForWidth(self.levelsDockWidget.sizePolicy().hasHeightForWidth())
#        self.levelsDockWidget.setSizePolicy(sizePolicy)
#        self.levelsDockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
#        self.levelsDockWidget.setObjectName("levelsDockWidget")
#        self.levelsDockWidgetContents = QtWidgets.QWidget()
#        self.levelsDockWidgetContents.setObjectName("levelsDockWidgetContents")
#        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.levelsDockWidgetContents)
#        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
#        self.verticalLayout_6.setObjectName("verticalLayout_6")
#        self.histogramPlotLayout = GraphicsLayoutWidget(self.levelsDockWidgetContents)
#        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
#        sizePolicy.setHorizontalStretch(0)
#        sizePolicy.setVerticalStretch(0)
#        sizePolicy.setHeightForWidth(self.histogramPlotLayout.sizePolicy().hasHeightForWidth())
#        self.histogramPlotLayout.setSizePolicy(sizePolicy)
#        self.histogramPlotLayout.setObjectName("histogramPlotLayout")
#        self.verticalLayout_6.addWidget(self.histogramPlotLayout)
#        self.levelsDockWidget.setWidget(self.levelsDockWidgetContents)
#        QIcmGuiMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.levelsDockWidget)
#        self.action_Settings = QtWidgets.QAction(QIcmGuiMainWindow)
#        self.action_Settings.setObjectName("action_Settings")
#        self.action_Quit = QtWidgets.QAction(QIcmGuiMainWindow)
#        self.action_Quit.setObjectName("action_Quit")
#        self.action_About = QtWidgets.QAction(QIcmGuiMainWindow)
#        self.action_About.setObjectName("action_About")
#        self.menu_File.addAction(self.action_Settings)
#        self.menu_File.addSeparator()
#        self.menu_File.addAction(self.action_Quit)
#        self.menu_Help.addAction(self.action_About)
#        self.menubar.addAction(self.menu_File.menuAction())
#        self.menubar.addAction(self.menu_Help.menuAction())
#        self.label_2.setBuddy(self.startFreqSpinBox)
#        self.label_3.setBuddy(self.stopFreqSpinBox)
#        self.label.setBuddy(self.binSizeSpinBox)
#        self.label_4.setBuddy(self.intervalSpinBox)
#        self.label_6.setBuddy(self.gainSpinBox)
#        self.label_5.setBuddy(self.ppmSpinBox)
#        self.label_7.setBuddy(self.cropSpinBox)

#        self.retranslateUi(QIcmGuiMainWindow)
#        QtCore.QMetaObject.connectSlotsByName(QIcmGuiMainWindow)
#        QIcmGuiMainWindow.setTabOrder(self.startButton, self.stopButton)
#        QIcmGuiMainWindow.setTabOrder(self.stopButton, self.singleShotButton)
#        QIcmGuiMainWindow.setTabOrder(self.singleShotButton, self.startFreqSpinBox)
#        QIcmGuiMainWindow.setTabOrder(self.startFreqSpinBox, self.stopFreqSpinBox)
#        QIcmGuiMainWindow.setTabOrder(self.stopFreqSpinBox, self.binSizeSpinBox)
#        QIcmGuiMainWindow.setTabOrder(self.binSizeSpinBox, self.intervalSpinBox)
#        QIcmGuiMainWindow.setTabOrder(self.intervalSpinBox, self.gainSpinBox)
#        QIcmGuiMainWindow.setTabOrder(self.gainSpinBox, self.ppmSpinBox)
#        QIcmGuiMainWindow.setTabOrder(self.ppmSpinBox, self.cropSpinBox)
#        QIcmGuiMainWindow.setTabOrder(self.cropSpinBox, self.mainCurveCheckBox)
#        QIcmGuiMainWindow.setTabOrder(self.mainCurveCheckBox, self.colorsButton)
#        QIcmGuiMainWindow.setTabOrder(self.colorsButton, self.peakHoldMaxCheckBox)
#        QIcmGuiMainWindow.setTabOrder(self.peakHoldMaxCheckBox, self.peakHoldMinCheckBox)
#        QIcmGuiMainWindow.setTabOrder(self.peakHoldMinCheckBox, self.averageCheckBox)
#        QIcmGuiMainWindow.setTabOrder(self.averageCheckBox, self.smoothCheckBox)
#        QIcmGuiMainWindow.setTabOrder(self.smoothCheckBox, self.smoothButton)
#        QIcmGuiMainWindow.setTabOrder(self.smoothButton, self.persistenceCheckBox)
#        QIcmGuiMainWindow.setTabOrder(self.persistenceCheckBox, self.persistenceButton)
#        QIcmGuiMainWindow.setTabOrder(self.persistenceButton, self.baselineCheckBox)
#        QIcmGuiMainWindow.setTabOrder(self.baselineCheckBox, self.baselineButton)
#        QIcmGuiMainWindow.setTabOrder(self.baselineButton, self.subtractBaselineCheckBox)
#        QIcmGuiMainWindow.setTabOrder(self.subtractBaselineCheckBox, self.histogramPlotLayout)
#        QIcmGuiMainWindow.setTabOrder(self.histogramPlotLayout, self.mainPlotLayout)
#        QIcmGuiMainWindow.setTabOrder(self.mainPlotLayout, self.waterfallPlotLayout)
    
    def retranslateUi(self, QIcmGuiMainWindow):
        _translate = QtCore.QCoreApplication.translate
        QIcmGuiMainWindow.setWindowTitle(_translate("QIcmGuiMainWindow", "QSpectrumAnalyzer"))
        self.menu_File.setTitle(_translate("QIcmGuiMainWindow", "&File"))
        self.menu_Help.setTitle(_translate("QIcmGuiMainWindow", "&Help"))
        self.controlsDockWidget.setWindowTitle(_translate("QIcmGuiMainWindow", "Controls"))
        self.startButton.setText(_translate("QIcmGuiMainWindow", "&Start"))
        self.stopButton.setText(_translate("QIcmGuiMainWindow", "S&top"))
        self.singleShotButton.setText(_translate("QIcmGuiMainWindow", "Si&ngle shot"))
        self.frequencyDockWidget.setWindowTitle(_translate("QIcmGuiMainWindow", "Frequency"))
        self.label_2.setText(_translate("QIcmGuiMainWindow", "Start:"))
        self.startFreqSpinBox.setSuffix(_translate("QIcmGuiMainWindow", " MHz"))
        self.label_3.setText(_translate("QIcmGuiMainWindow", "Stop:"))
        self.stopFreqSpinBox.setSuffix(_translate("QIcmGuiMainWindow", " MHz"))
        self.label.setText(_translate("QIcmGuiMainWindow", "&Bin size:"))
        self.binSizeSpinBox.setSuffix(_translate("QIcmGuiMainWindow", " kHz"))
        self.settingsDockWidget.setWindowTitle(_translate("QIcmGuiMainWindow", "Settings"))
        self.label_4.setText(_translate("QIcmGuiMainWindow", "&Interval [s]:"))
        self.label_6.setText(_translate("QIcmGuiMainWindow", "&Gain [dB]:"))
        self.label_5.setText(_translate("QIcmGuiMainWindow", "Corr. [ppm]:"))
        self.label_7.setText(_translate("QIcmGuiMainWindow", "Crop [%]:"))
        self.mainCurveCheckBox.setText(_translate("QIcmGuiMainWindow", "Main curve"))
        self.colorsButton.setText(_translate("QIcmGuiMainWindow", "Colors..."))
        self.peakHoldMaxCheckBox.setText(_translate("QIcmGuiMainWindow", "Max. hold"))
        self.peakHoldMinCheckBox.setText(_translate("QIcmGuiMainWindow", "Min. hold"))
        self.averageCheckBox.setText(_translate("QIcmGuiMainWindow", "Average"))
        self.smoothCheckBox.setText(_translate("QIcmGuiMainWindow", "Smoothing"))
        self.smoothButton.setText(_translate("QIcmGuiMainWindow", "..."))
        self.persistenceCheckBox.setText(_translate("QIcmGuiMainWindow", "Persistence"))
        self.persistenceButton.setText(_translate("QIcmGuiMainWindow", "..."))
        self.gainSpinBox.setSpecialValueText(_translate("QIcmGuiMainWindow", "auto"))
        self.baselineCheckBox.setText(_translate("QIcmGuiMainWindow", "Baseline"))
        self.baselineButton.setText(_translate("QIcmGuiMainWindow", "..."))
        self.subtractBaselineCheckBox.setText(_translate("QIcmGuiMainWindow", "Subtract baseline"))
        self.levelsDockWidget.setWindowTitle(_translate("QIcmGuiMainWindow", "Levels"))
        self.action_Settings.setText(_translate("QIcmGuiMainWindow", "&Settings..."))
        self.action_Quit.setText(_translate("QIcmGuiMainWindow", "&Quit"))
        self.action_Quit.setShortcut(_translate("QIcmGuiMainWindow", "Ctrl+Q"))
        self.action_About.setText(_translate("QIcmGuiMainWindow", "&About"))